name: JDK19

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/jdk19.yml'
      - 'Casks/zulu-jdk19.rb'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/jdk19.yml'
      - 'Casks/zulu-jdk19.rb'

jobs:
  check:
    uses: goooler/homebrew-zulu/.github/workflows/reusable-cask-checks.yml@master
    with:
      jdk-version: 19
