name: JDK16

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/jdk16.yml'
      - 'Casks/zulu-jdk16.rb'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/jdk16.yml'
      - 'Casks/zulu-jdk16.rb'

jobs:
  check:
    uses: goooler/homebrew-zulu/.github/workflows/reusable-cask-checks.yml@master
    with:
      jdk-version: 16
