name: JDK11

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/reusable-cask-checks.yml'
      - 'Casks/zulu-jdk11.rb'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/reusable-cask-checks.yml'
      - 'Casks/zulu-jdk11.rb'

jobs:
  check:
    uses: mdogan/homebrew-zulu/.github/workflows/reusable-cask-checks.yml@master
    with:
      jdk-version: 11
