name: JDK15

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/jdk15.yml'
      - 'Casks/zulu-jdk15.rb'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/jdk15.yml'
      - 'Casks/zulu-jdk15.rb'

jobs:
  check:
    uses: goooler/homebrew-zulu/.github/workflows/reusable-cask-checks.yml@master
    with:
      jdk-version: 15
